### PR TITLE
Show tests prints

### LINKED ISSUE #262: View a specific exercise's stdout
Hi there,

I'm working through rustlings on a Windows machine. It's a wonderful resource - thank-you so much for putting the effort into making it.

One thing I have yet to figure out is how to view the output of the current exercise. Currently I just see if an exercise compiles (and the compile errors if not). However, if an exercise uses `println!` it would be lovely to be able to see that output somewhere.

Am I doing something wrong or is this something that's yet to be implemented?

### PR DESCRIPTION
**Pull request by AbdouSeck**
This new feature can be accessed by invoking rustlings with `--nocapture`.

closes #262

**_MINOR CHANGES_**:
    * Documentation added to source code under [`src`](https://github.com/rust-lang/rustlings/tree/master/src)
    * Both unit and integration tests for `--nocapture` have been added.

**_BREAKING CHANGES_**:
The following function take a new boolean argument:
    * `run`
    * `verify`
    * `test`
    * `compile_and_test`

`compile_and_test` is the function that uses this new boolean argument to determine whether or not to display the output from the test harnesses.

Please feel free to reach out with any questions.

Thank you,

Abdou

### CODE REVIEW

**Comment by jrvidal** [comment]
ack, I'll look into this ASAP

File: src/verify.rs [hunk 1]
```diff
@@ -73,7 +88,10 @@ fn compile_and_test(exercise: &Exercise, run_mode: RunMode) -> Result<bool, ()>
     progress_bar.finish_and_clear();
 
     match result {
-        Ok(_) => {
+        Ok(output) => {
+            if verbose {
+                println!("{}", output.stdout);
```
Comment (jrvidal) [inline src/verify.rs:93]: I'm starting to think that we should be a bit more sophisticated while handling the output of exercises, and try to have both stdout and stderr merged as they would appear in the terminal screen.

Anyway, out of scope, just thinking out loud.

Comment (AbdouSeck) [reply src/verify.rs:93]: @jrvidal thanks for the review! I agree with providing more information to the end users as long as there is a way to control that; like with command line options to make output `--quiet` or `--verbose`.

Normally, an exercise's standard error should be empty unless there is a complication error or a runtime one. Unless someone explicitly uses `eprint!` or `eprintln!` (or the many other ways of writing to targeted file handles) in their code to solve an exercise, there should be nothing in the standard error. So, keeping standard output and error separate may actually come in handy when trying to figure out if a user actually wrote to the standard error.

I am open to discussing this further, though.

Thanks!

Abdou

**Comment by AbdouSeck** [comment]
I decided to a commit which hopefully closes #423. I just added a couple of steps to check for string emptiness and use `master` as the backup for installing the program when the latest tag can't be obtained.

Thanks,

Abdou

**Comment by AbdouSeck** [comment]
@fmoko please let me know if this needs additional work to get it merged.

Thanks,

Abdou

**Comment by fmoko** [comment]
@AbdouSeck All good! Just went under my radar.

File: src/verify.rs (hunk 1 above)
Comment (mo8it) [reply src/verify.rs:93]: > I'm starting to think that we should be a bit more sophisticated while handling the output of exercises, and try to have both stdout and stderr merged as they would appear in the terminal screen.
> 
> Anyway, out of scope, just thinking out loud.

Done in the `v6` branch with `os_pipe` :D
